

# Bootcamp specifics
- name: Set bootcamp specific details
  hosts: bootcamp
  roles:
    - bootcamp-clustername
    - bootcamp-http-port
    - bootcamp-permissions



# - name: Apply MapR pre-requisite configuration to all nodes
#   hosts: all
#   roles:
#     - common-prereq-software
 - name: Create MapR Repository and MapR Group and User
   hosts: all
   roles:
     - configure-mapr-repository




## Install MapR Monitoring

# - name: Install Elasticsearch
#   hosts: mapr-elasticsearch
#   roles:
#     - mapr-elasticsearch
# - name: Install Kibana
#   hosts: mapr-kibana
#   roles:
#     - mapr-kibana
# - name: Install Fluentd
#   hosts: mapr-fluentd
#   roles:
#     - mapr-fluentd

# - name: Install OpenTSDB
#   hosts: mapr-opentsdb
#   roles:
#     - mapr-opentsdb
# - name: Install Grafana
#   hosts: mapr-grafana
#   roles:
#     - mapr-grafana
# - name: Install Collectd
#   hosts: mapr-collectd
#   roles:
#     - mapr-collectd


## Install MapR Eco-system components
# - name: Install Drill
#   hosts: mapr-drill
#   roles:
#     - mapr-drill
# - name: Install YARN Resource Manager
#   hosts: mapr-resourcemanager
#   roles:
#     - mapr-resourcemanager
# - name: Install YARN Node Manager(s)
#   hosts: mapr-nodemanager
#   roles:
#     - mapr-nodemanager
# - name: Install Spark on YARN
#   hosts: mapr-spark-yarn
#   roles:
#     - mapr-spark-yarn
# - name: Install Spark History Server
#   hosts: mapr-spark-historyserver
#   roles:
#     - mapr-spark-historyserver



# # Configure and Start Zookeeper & Warden
# - name: Configure and start
#   hosts: all
#   roles:
#     - mapr-configure-unsecure
# - name: Restarting mapr-zookeeper
#   hosts: mapr-zookeeper
#   roles:
#     - mapr-configure-zookeeper-restart
# - name: Restarting mapr-warden
#   hosts: all
#   roles:
#     - mapr-configure-warden-restart
