---
   - name: Download Kibana
     get_url:
       url: "{{kibana_download_url}}"
       dest: "{{kibana_download_location}}/elasticsearch-{{kibana_version}}.rpm"
       timeout: 900

   - name: Install Kibana
     yum: name={{kibana_download_location}}/elasticsearch-{{kibana_version}}.rpm state=present
