---
   - name: Download Kibana
     get_url:
       url: "{{kibana_download_url}}"
       dest: "{{kibana_download_location}}/elasticsearch-{{kibana_version}}.rpm"
       timeout: 900

   - name: Install Kibana
     yum: name={{kibana_download_location}}/elasticsearch-{{kibana_version}}.rpm state=present

   - name: Allow Elasticsearch to bind to all IP addresses
     shell: 'echo "server.host: 0.0.0.0" >> /etc/kibana/kibana.yml'

   - Start the Kibana service
     service:
     name: kibana
     state: restarted

   - name: Wait for Kibana to come up
     wait_for:
       port: "{{kibana_port}}"
       delay: 5
