---
# Install MapR MCS
# Redhat / CentOS
- name: Install mapr-webserver (Redhat / CentOS)
  yum: name=mapr-webserver state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-webserver (Debian / Ubuntu)
  apt: name=mapr-webserver state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-webserver (Suse)
  zypper: name=mapr-webserver state=present
  when: ansible_os_family == 'Suse'