---
   - name: Creates Data directory
     file: path={{lab_dataset_install_location}} state=directory

   - name: Extract Zeppelin Lab Datasets
     unarchive:
       src={{lab_dataset_download_location}}/{{item}}
       dest={{lab_dataset_install_location}}
       copy=no
     with_items:
     - "{{lab_dataset_filename_lab2}}"
     - "{{lab_dataset_filename_lab6}}"

   - name: Copy Drill dataset
     copy:
       src={{drill_lab_dataset_download_location}}/{{item}}
       dest={{lab_dataset_install_location}}
     with_items:
     - "{{drill_lab_dataset_filename_lab4}}"

   - name: Wait for Drill to come up
     wait_for:
       port: "{{drill_port}}"
       delay: 5

   - name: Update Apache Drill DFS storage plugin
     uri:
       url: "http://localhost:8047/storage/dfs.json"
       method: POST
       body: "{{ lookup('file' , '{{drill_storage_plugin_dfs}}') }}"
       body_format: json
       return_content: yes
     register: drill_storage_plugin_result

   - name: Check if the DFS storage plugin got created successfully in Drill
     fail:
     when: "'success' not in drill_storage_plugin_result.content"

