---
    # Change MapR Cluster Name to training.mapr.com
   - name: Ensure TCP retries are set to 5
     lineinfile: dest=/opt/mapr/conf/mapr-clusters.conf regexp="^([\w.]+ )" line="training.mapr.com" insertbefore=" secure"
#   - replace: 
#    dest: /opt/mapr/conf/mapr-clusters.conf
#    regexp: '^([\w.]+ )'
#    replace: 'training.mapr.com'

         #dest=/etc/sudoers regexp="^root(\s+)ALL=(ALL)(\s+)ALL" insertafter="^root" line='{{ item }}' state=present