---
    # Change MapR Cluster Name to training.mapr.com
   - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $1}'"
     register: clustersname

   - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $2}'"
     register: clustersecure

   - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $3}'"
     register: clustercldbnodes

#   - name: Ensure TCP retries are set to 5
     lineinfile: dest=/opt/mapr/conf/mapr-clusters.conf regexp="^{{ clustersname }}" line="{{ bootcamp_cluster_name }} {{ clustersecure }} {{ clustercldbnodes }}"

#   - replace: 
#    dest: /opt/mapr/conf/mapr-clusters.conf
#    regexp: "^{{ clustersname }}"
#    replace: "training.mapr.com"

#dest=/etc/sudoers regexp="^root(\s+)ALL=(ALL)(\s+)ALL" insertafter="^root" line='{{ item }}' state=present