---
   - name: Change MapR Cluster Name to {{bootcamp_cluster_name}}
     shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $1}'"
     register: clustername

   - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $2}'"
     register: clustersecure

   - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $3}'"
     register: clustercldbnodes

   - debug:
       msg: "Current content of mapr-clusters.conf: {{clustername.stdout}} {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

   - debug:
       msg: "New content of mapr-clusters.conf: {{bootcamp_cluster_name}} {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

   - shell: echo {{bootcamp_cluster_name}} {{clustersecure.stdout}} {{clustercldbnodes.stdout}}  > /opt/mapr/conf/mapr-clusters.conf
