---
    # Download and install Maven
#   - name: Create Maven repo for yum
#     get_url:
#       url: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
#       dest: /etc/yum.repos.d/epel-apache-maven.repo

#   - name: Install Maven
#     yum: name=apache-maven state=present

   - name: Create SBT repo for yum
     get_url:
       url: https://bintray.com/sbt/rpm/rpm
       dest: /etc/yum.repos.d/bintray-sbt-rpm.repo

   - name: Install Maven
     yum: name=sbt state=present

   - name: Clone twitter-sentiment-analysis github project
     git:
       repo: https://github.com/mapr-emea/twitter-sentiment-analysis
       dest: /tmp/twitter-sentiment-analysis
#       version: release-0.22

#   - name: Compile the Twitter Sentiment Analysis jar
#     shell: 
# JAVA_OPTS=-Xmx2G sbt assembly