---
   - name: Create SBT repo for yum to build and package twitter-sentiment-analysis
     get_url:
       url: https://bintray.com/sbt/rpm/rpm
       dest: /etc/yum.repos.d/bintray-sbt-rpm.repo

   - name: Install SBT
     yum: name=sbt state=present

   - name: Clone twitter-sentiment-analysis github project
     git:
       repo: "{{twitter_sentiment_github}}"
       dest: "{{twitter_sentiment_location}}"
#       version: "{{twitter_sentiment_github_version}}"

   - name: SBT clean compile twitter-sentiment-analysis github project
     shell: sbt clean compile
     args:
       chdir: "{{twitter_sentiment_location}}"

   - name: SBT assemply twitter-sentiment-analysis github project
     shell: JAVA_OPTS=-Xmx2G sbt assembly
     args:
       chdir: "{{twitter_sentiment_location}}"
