---
   - name: Clone Anchormen/spark_bootcamp github project
     git:
       repo: "{{anchormen_spark_bootcamp_github}}"
       dest: "{{anchormen_spark_bootcamp_location}}"
#       version: "{{anchormen_spark_bootcamp_github_version}}"

   - name: SBT clean package Anchormen/spark_bootcamp github project
     shell: sbt clean package
     args:
       chdir: "{{anchormen_spark_bootcamp_location}}"
