---
   - name: Clone Anchormen/spark_bootcamp github project
     git:
       repo: "{{anchormen_spark_bootcamp_github}}"
       dest: "{{anchormen_spark_bootcamp_location}}"
#       version: "{{anchormen_spark_bootcamp_github_version}}"

   - name: SBT clean compile Anchormen/spark_bootcamp github project
     shell: sbt clean compile
     args:
       chdir: "{{anchormen_spark_bootcamp_location}}"

   - name: SBT assemply Anchormen/spark_bootcamp github project
     shell: JAVA_OPTS=-Xmx2G sbt assembly
     args:
       chdir: "{{anchormen_spark_bootcamp_location}}"
