---
   - name: Clone Anchormen/spark-bootcamp github project
     git:
       repo: "{{anchormen_spark-bootcamp_github}}"
       dest: "{{anchormen_spark-bootcamp_location}}"
#       version: "{{anchormen_spark-bootcamp_github_version}}"

   - name: SBT clean compile twitter-sentiment-analysis github project
     shell: sbt clean compile
     args:
       chdir: "{{anchormen_spark-bootcamp_location}}"

   - name: SBT assemply twitter-sentiment-analysis github project
     shell: JAVA_OPTS=-Xmx2G sbt assembly
     args:
       chdir: "{{anchormen_spark-bootcamp_location}}"
