---
   - name: Download Elasticsearch
     get_url:
       url: "{{elasticsearch_download_url}}"
       dest: "{{elasticsearch_download_location}}/elasticsearch-{{elasticsearch_version}}.rpm"
       timeout: 900

   - name: Install Elasticsearch
     yum: name={{elasticsearch_download_location}}/elasticsearch-{{elasticsearch_version}}.rpm state=present

   - name: Allow Elasticsearch to bind to all IP addresses
     lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp="^network.bind_host" line="network.bind_host: 0.0.0.0"

   - name: Start the Elasticsearch service
     service:
       name: elasticsearch
       state: restarted

#   - name: Wait for Elasticsearch to come up
#     wait_for:
#       port: "{{elasticsearch_port}}"
#       delay: 5
