---
   - name: Download and extract Zeppelin
     unarchive:
       src: "{{zeppelin_download_url}}"
       dest: "/opt/"
       remote_src: yes

   - name: Download and extract Zeppelin
     command: "mv /opt/zeppelin* {{zeppelin_location}}"
     