---
   - name: Download and extract Zeppelin
     unarchive:
       src: "{{zeppelin_download_url}}"
       dest: "/opt/"
       remote_src: yes

   - name: Move zeppelin to required location
     command: "mv /opt/zeppelin-{{zeppelin_version}}-bin-all {{zeppelin_location}}"
     