---
   - name: Download and extract Zeppelin
     get_url:
       url: "{{zeppelin_download_url}}"
       dest: "{{zeppelin_download_location}}/zeppelin-{{zeppelin_version}}-bin-all.tgz"
       timeout: 900

   - name: Extract Zeppelin
     unarchive: src={{zeppelin_download_location}}/zeppelin-{{zeppelin_version}}-bin-all.tgz dest={{zeppelin_install_location}} copy=no

   - name: Start Zeppelin
     shell: "/opt/zeppelin-{{zeppelin_version}}-bin-all/bin/zeppelin-daemon.sh restart"

   - name: Wait for Zeppelin to come up
     wait_for:
       port: "{{zeppelin_port}}"
       delay: 5

   - name: Import lab notebooks into Zeppelin
     uri:
       url: "http://localhost:{{zeppelin_port}}/api/notebook/import"
       method: POST
       body: "{{ lookup('file' , '{{item}}') }}"
       status_code: 201
       body_format: json
     with_items:
     - "{{zeppelin_notebook_1}}"
     - "{{zeppelin_notebook_2}}"

