---
   - name: Download Zeppelin
     get_url:
       url: "{{zeppelin_download_url}}"
       dest: "{{zeppelin_download_location}}/zeppelin-{{zeppelin_version}}-bin-all.tgz"
       timeout: 900

   - name: Extract Zeppelin
     unarchive: src={{zeppelin_download_location}}/zeppelin-{{zeppelin_version}}-bin-all.tgz dest={{zeppelin_install_location}} copy=no

   - name: Copy zeppelin-site.xml.template to zeppelin-site.xml
     shell: "cp /{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/conf/zeppelin-site.xml.template /{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/conf/zeppelin-site.xml"

   - name: Set Zeppelin port number to {{zeppelin_port}} in zeppelin-site.xml
     lineinfile: dest=/{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/conf/zeppelin-site.xml regexp="^  <value>8080</value>" line="  <value>{{zeppelin_port}}</value>"

   - name: Launch Zeppelin on system start
     lineinfile: dest=/etc/rc.d/rc.local line="/{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/bin/zeppelin-daemon.sh restart" state=present

   - name: Delete all existing Zeppelin notebooks
     shell: "rm -rf /{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/notebook/*"

   - name: Start Zeppelin
     shell: "/{{zeppelin_install_location}}/zeppelin-{{zeppelin_version}}-bin-all/bin/zeppelin-daemon.sh restart"

   - name: Wait for Zeppelin to come up
     wait_for:
       port: "{{zeppelin_port}}"
       delay: 5

   - name: Import lab notebooks into Zeppelin
     uri:
       url: "http://localhost:{{zeppelin_port}}/api/notebook/import"
       method: POST
       body: "{{ lookup('file' , '{{item}}') }}"
       status_code: 201
       body_format: json
     with_items:
     - "{{zeppelin_notebook_1}}"
     - "{{zeppelin_notebook_2}}"
